# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  TicTacToe_config = debug
endif
ifeq ($(config),release)
  TicTacToe_config = release
endif

PROJECTS := TicTacToe

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

TicTacToe:
ifneq (,$(TicTacToe_config))
	@echo "==== Building TicTacToe ($(TicTacToe_config)) ===="
	@${MAKE} --no-print-directory -C . -f TicTacToe.make config=$(TicTacToe_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f TicTacToe.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TicTacToe"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"